version: 2
machine:
  python:
    version: 3.6.2
jobs:
    build:
        docker:
            - image: ubuntu:16.04
        environment:
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        steps:
            - checkout
            - run:
                name: install pre-dependencies
                command: |
                    apt update
                    apt install curl python3-pip -y
                    pip3 install -r requirements.txt
            - run:
                name: install dependencies
                command: |
                    curl -sL https://deb.nodesource.com/setup_9.x | bash
                    apt install nodejs git -y
                    npm install ganache-cli -g
                    npm install

            - run:
                name: run test
                command: |
                  ganache-cli &
                  truffle test --network dev
